import {
  Heart,
  Play,
  Music2,
  Send,
  MessageCircle,
  Globe,
} from "lucide-react";

export const services = [
  {
    id: 1,
    title: "Instagram Followers",
    category: "Instagram",
    icon: Heart,
    price: 10,
    min: 100,
    max: 100000,
    speed: "Fast",
  },
  {
    id: 2,
    title: "Instagram Likes",
    category: "Instagram",
    icon: Heart,
    price: 6,
    min: 100,
    max: 50000,
    speed: "Fast",
  },
  {
    id: 3,
    title: "TikTok Likes",
    category: "TikTok",
    icon: Music2,
    price: 8,
    min: 100,
    max: 100000,
    speed: "Medium",
  },
  {
    id: 4,
    title: "TikTok Views",
    category: "TikTok",
    icon: Music2,
    price: 4,
    min: 1000,
    max: 1000000,
    speed: "Fast",
  },
  {
    id: 5,
    title: "YouTube Views",
    category: "YouTube",
    icon: Play,
    price: 12,
    min: 1000,
    max: 1000000,
    speed: "Fast",
  },
  {
    id: 6,
    title: "Telegram Members",
    category: "Telegram",
    icon: Send,
    price: 14,
    min: 100,
    max: 50000,
    speed: "Medium",
  },
  {
    id: 7,
    title: "WhatsApp Traffic",
    category: "WhatsApp",
    icon: MessageCircle,
    price: 18,
    min: 100,
    max: 50000,
    speed: "Slow",
  },
  {
    id: 8,
    title: "Facebook Followers",
    category: "Facebook",
    icon: Globe,
    price: 9,
    min: 100,
    max: 50000,
    speed: "Fast",
  },
];